"""מערכת לקחים — schema `lessons` (PLAN-lessons-module.md §2.2).

The module's 17 tables live in their own schema so PostgREST can expose them
without ever seeing a Shan-AI table. Everything here is idempotent and runs at
startup (`ensure_schema`), next to the existing ALTERs in `app/main.py`.

Rules a test enforces:
- No statement in SCHEMA_STATEMENTS names `public.` except the two
  `REFERENCES public.users(id)` links — this module never issues DDL against
  Shan-AI's own tables.
- `lessons.profiles` has no password column (login is Shan-AI's).
- Every function pins `search_path` to `lessons`.

Role statements (ROLE_STATEMENTS) run separately and best-effort: CREATE ROLE
needs CREATEROLE, and a missing privilege must never stop the app booting.
"""
from __future__ import annotations

import logging
import os
import re

from sqlalchemy import text

logger = logging.getLogger(__name__)

SCHEMA = "lessons"
# The role PostgREST switches to for every request, and the one it logs in as.
ANON_ROLE = "lessons_anon"
AUTHENTICATOR_ROLE = "lessons_authenticator"

# Load order respects foreign keys (the P3 import walks the same list).
TABLES: tuple[str, ...] = (
    "profiles", "equipment", "lesson_categories", "projects", "lessons",
    "lesson_implementations", "lesson_workflow_events", "referent_reviews",
    "form_field_configs", "form_field_options", "feedback", "notifications", "activity_logs",
    "ai_feedback", "ai_candidate_insights", "ai_global_insights", "ai_user_preferences",
)

_SEQUENCES: tuple[tuple[str, str], ...] = (
    ("equipment_id_seq", "equipment"),
    ("projects_id_seq", "projects"),
    ("lessons_id_seq", "lessons"),
    ("notifications_id_seq", "notifications"),
    ("lesson_implementations_id_seq", "lesson_implementations"),
    ("lesson_categories_id_seq", "lesson_categories"),
    ("feedback_id_seq", "feedback"),
    ("form_field_configs_id_seq", "form_field_configs"),
    ("form_field_options_id_seq", "form_field_options"),
    ("ai_feedback_id_seq", "ai_feedback"),
    ("ai_user_preferences_id_seq", "ai_user_preferences"),
    ("ai_candidate_insights_id_seq", "ai_candidate_insights"),
    ("ai_global_insights_id_seq", "ai_global_insights"),
    ("lesson_workflow_events_id_seq", "lesson_workflow_events"),
)

# Arbitrary constant: two containers booting at once take turns on the DDL
# instead of racing CREATE OR REPLACE FUNCTION ("tuple concurrently updated").
_ADVISORY_LOCK = 7_340_518_201

_TABLE_DDL: tuple[str, ...] = (
    """CREATE TABLE IF NOT EXISTS lessons.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL, user_name text NOT NULL, user_email text NOT NULL, user_role text NOT NULL,
  action_type text NOT NULL, entity_type text NOT NULL, entity_id text,
  object_label text NOT NULL DEFAULT '', description text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE IF NOT EXISTS lessons.ai_candidate_insights (
  id integer NOT NULL DEFAULT nextval('lessons.ai_candidate_insights_id_seq') PRIMARY KEY,
  insight_text text NOT NULL, context_type text NOT NULL DEFAULT 'general', context_value text,
  source_feedback_ids jsonb DEFAULT '[]'::jsonb, frequency integer NOT NULL DEFAULT 1,
  confidence integer NOT NULL DEFAULT 50, status text NOT NULL DEFAULT 'pending',
  admin_notes text, reviewed_by text, reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE IF NOT EXISTS lessons.ai_feedback (
  id integer NOT NULL DEFAULT nextval('lessons.ai_feedback_id_seq') PRIMARY KEY,
  user_id text NOT NULL, user_name text NOT NULL, context_type text NOT NULL DEFAULT 'dashboard',
  context_id text, feedback_text text NOT NULL, classification text DEFAULT 'pending',
  user_override_classification text, extracted_mistakes jsonb DEFAULT '[]'::jsonb,
  extracted_preferences jsonb DEFAULT '[]'::jsonb, processed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE IF NOT EXISTS lessons.ai_global_insights (
  id integer NOT NULL DEFAULT nextval('lessons.ai_global_insights_id_seq') PRIMARY KEY,
  candidate_id integer REFERENCES lessons.ai_candidate_insights(id) ON DELETE SET NULL,
  insight_text text NOT NULL, context_type text NOT NULL DEFAULT 'general', context_value text,
  approved_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE IF NOT EXISTS lessons.ai_user_preferences (
  id integer NOT NULL DEFAULT nextval('lessons.ai_user_preferences_id_seq') PRIMARY KEY,
  user_id text NOT NULL, preference_key text NOT NULL, preference_value text NOT NULL,
  source_feedback_id integer REFERENCES lessons.ai_feedback(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, preference_key))""",
    """CREATE TABLE IF NOT EXISTS lessons.equipment (
  id integer NOT NULL DEFAULT nextval('lessons.equipment_id_seq') PRIMARY KEY,
  name text NOT NULL, category text NOT NULL)""",
    """CREATE TABLE IF NOT EXISTS lessons.feedback (
  id integer NOT NULL DEFAULT nextval('lessons.feedback_id_seq') PRIMARY KEY,
  user_id text NOT NULL, user_name text NOT NULL, type text NOT NULL DEFAULT 'general',
  title text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'open',
  admin_notes text DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz)""",
    """CREATE TABLE IF NOT EXISTS lessons.form_field_configs (
  id integer NOT NULL DEFAULT nextval('lessons.form_field_configs_id_seq') PRIMARY KEY,
  form_type text NOT NULL, field_key text NOT NULL, display_name text NOT NULL,
  is_required boolean NOT NULL DEFAULT false, is_visible boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0, section text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (form_type, field_key))""",
    """CREATE TABLE IF NOT EXISTS lessons.form_field_options (
  id integer NOT NULL DEFAULT nextval('lessons.form_field_options_id_seq') PRIMARY KEY,
  field_config_id integer NOT NULL REFERENCES lessons.form_field_configs(id) ON DELETE CASCADE,
  value text NOT NULL, label text NOT NULL, is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now())""",
    """CREATE TABLE IF NOT EXISTS lessons.lesson_categories (
  id integer NOT NULL DEFAULT nextval('lessons.lesson_categories_id_seq') PRIMARY KEY,
  name text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now())""",
    # shan_project_identifier: optional link to a Shan-AI project, set by an
    # admin only. No FK — Shan-AI projects deactivate and reappear by identifier.
    """CREATE TABLE IF NOT EXISTS lessons.projects (
  id integer NOT NULL DEFAULT nextval('lessons.projects_id_seq') PRIMARY KEY,
  name text NOT NULL, stage_index integer NOT NULL DEFAULT 0, risk text NOT NULL DEFAULT 'low',
  lessons_count integer NOT NULL DEFAULT 0, equipment_ids integer[] NOT NULL DEFAULT '{}',
  project_type text NOT NULL DEFAULT 'new_build', station_type text NOT NULL DEFAULT 'closed',
  manager_id text NOT NULL, site text, stage_indexes integer[] NOT NULL DEFAULT '{0}',
  shan_project_identifier varchar(100),
  CONSTRAINT projects_stage_indexes_min_check CHECK (array_length(stage_indexes, 1) >= 1))""",
    """CREATE TABLE IF NOT EXISTS lessons.lessons (
  id integer NOT NULL DEFAULT nextval('lessons.lessons_id_seq') PRIMARY KEY,
  title text NOT NULL, description text NOT NULL DEFAULT '', project_name text NOT NULL,
  project_id integer REFERENCES lessons.projects(id) ON DELETE SET NULL,
  stage text NOT NULL, category text NOT NULL, risk text NOT NULL DEFAULT 'low',
  status text NOT NULL DEFAULT 'new', date text NOT NULL DEFAULT '', created_by text NOT NULL,
  approved_by text, distributed_to integer[], equipment_ids integer[] NOT NULL DEFAULT '{}',
  ai_review jsonb, recommendation text NOT NULL DEFAULT '', skip_distribution boolean NOT NULL DEFAULT false,
  distributed_to_referents text[], professional_domain text, event_date text, assigned_to text,
  workflow_status text NOT NULL DEFAULT 'חדש', impact_schedule_delay integer, impact_budget_cost integer,
  impact_quality_desc text, file_url text, referent_start_date text, target_date text, closed_date text,
  updated_at timestamptz NOT NULL DEFAULT now(), return_reason text, return_date text, returned_by text)""",
    """CREATE TABLE IF NOT EXISTS lessons.lesson_implementations (
  id integer NOT NULL DEFAULT nextval('lessons.lesson_implementations_id_seq') PRIMARY KEY,
  lesson_id integer NOT NULL REFERENCES lessons.lessons(id) ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES lessons.projects(id) ON DELETE CASCADE,
  reason text NOT NULL DEFAULT '', priority text NOT NULL DEFAULT 'medium',
  is_relevant boolean, is_implemented boolean, notes text, responded_by text, responded_at timestamptz,
  CONSTRAINT unique_lesson_project UNIQUE (lesson_id, project_id))""",
    """CREATE TABLE IF NOT EXISTS lessons.lesson_workflow_events (
  id bigint NOT NULL DEFAULT nextval('lessons.lesson_workflow_events_id_seq') PRIMARY KEY,
  lesson_id integer NOT NULL REFERENCES lessons.lessons(id) ON DELETE CASCADE,
  event_type text NOT NULL, status_before text, status_after text,
  actor_id text NOT NULL, actor_name text NOT NULL, actor_role text NOT NULL,
  target_user_id text, target_user_name text, note text,
  created_at timestamptz NOT NULL DEFAULT now(), recovered_from_log_id bigint)""",
    """CREATE TABLE IF NOT EXISTS lessons.notifications (
  id integer NOT NULL DEFAULT nextval('lessons.notifications_id_seq') PRIMARY KEY,
  user_id text NOT NULL, type text NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '',
  "time" text NOT NULL DEFAULT (now())::text, read boolean NOT NULL DEFAULT false,
  entity_id text, entity_type text)""",
    # No password column: login is Shan-AI's. shan_user_id links a person to a
    # Shan-AI user (SET NULL — deleting that user only drops the link).
    # is_login is false for referent groups and historical names.
    """CREATE TABLE IF NOT EXISTS lessons.profiles (
  id text PRIMARY KEY, name text NOT NULL, email text NOT NULL,
  role text NOT NULL DEFAULT 'project_manager', assigned_projects integer[] NOT NULL DEFAULT '{}',
  email_preferences jsonb NOT NULL DEFAULT '{"approved": true, "rejected": true, "new_lesson": true, "distributed": true, "stage_change": true, "ai_suggestion": true}'::jsonb,
  assigned_equipment_ids integer[] NOT NULL DEFAULT '{}',
  assigned_stage_indexes integer[] NOT NULL DEFAULT '{}',
  shan_user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
  is_login boolean NOT NULL DEFAULT true)""",
    """CREATE TABLE IF NOT EXISTS lessons.referent_reviews (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lesson_id integer NOT NULL REFERENCES lessons.lessons(id) ON DELETE CASCADE,
  referent_id text NOT NULL, reason text NOT NULL DEFAULT '', priority text NOT NULL DEFAULT 'medium',
  is_relevant boolean, is_implemented boolean, notes text, responded_at timestamptz,
  decision text, response_text text)""",
    # Referent groups (owner decision 4): Shan-AI users who act for a referent
    # profile. Not exposed to PostgREST — managed by admins through Shan-AI.
    """CREATE TABLE IF NOT EXISTS lessons.referent_members (
  profile_id text NOT NULL REFERENCES lessons.profiles(id) ON DELETE CASCADE,
  shan_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  PRIMARY KEY (profile_id, shan_user_id))""",
)

_FUNCTION_DDL: tuple[str, ...] = (
    """CREATE OR REPLACE FUNCTION lessons.apply_lesson_workflow_event(p_lesson_id integer, p_event_type text, p_status_after text, p_actor_id text, p_actor_name text, p_actor_role text, p_lesson_updates jsonb DEFAULT '{}'::jsonb, p_note text DEFAULT NULL::text, p_target_user_id text DEFAULT NULL::text, p_target_user_name text DEFAULT NULL::text)
 RETURNS lessons.lesson_workflow_events LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'lessons'
AS $function$
DECLARE
  v_status_before TEXT;
  v_event lessons.lesson_workflow_events;
BEGIN
  IF p_actor_role = 'viewer' THEN
    RAISE EXCEPTION 'viewer role cannot modify lesson workflow';
  END IF;
  SELECT workflow_status INTO v_status_before FROM lessons.lessons WHERE id = p_lesson_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'lesson % not found', p_lesson_id;
  END IF;
  IF p_lesson_updates IS NOT NULL AND p_lesson_updates <> '{}'::jsonb THEN
    UPDATE lessons.lessons AS l
    SET workflow_status   = COALESCE(u.workflow_status, l.workflow_status),
        status            = COALESCE(u.status, l.status),
        assigned_to       = COALESCE(u.assigned_to, l.assigned_to),
        referent_start_date = COALESCE(u.referent_start_date, l.referent_start_date),
        closed_date       = COALESCE(u.closed_date, l.closed_date),
        return_reason     = CASE WHEN p_lesson_updates ? 'return_reason' THEN u.return_reason ELSE l.return_reason END,
        return_date       = CASE WHEN p_lesson_updates ? 'return_date' THEN u.return_date ELSE l.return_date END,
        returned_by       = CASE WHEN p_lesson_updates ? 'returned_by' THEN u.returned_by ELSE l.returned_by END
    FROM jsonb_populate_record(NULL::lessons.lessons, p_lesson_updates) AS u
    WHERE l.id = p_lesson_id;
  END IF;
  INSERT INTO lessons.lesson_workflow_events (
    lesson_id, event_type, status_before, status_after,
    actor_id, actor_name, actor_role, target_user_id, target_user_name, note
  ) VALUES (
    p_lesson_id, p_event_type, v_status_before, COALESCE(p_status_after, v_status_before),
    p_actor_id, p_actor_name, p_actor_role, p_target_user_id, p_target_user_name, p_note
  )
  RETURNING * INTO v_event;
  RETURN v_event;
END;
$function$""",
    """CREATE OR REPLACE FUNCTION lessons.sync_project_stage_index() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'lessons'
AS $function$
BEGIN
  IF NEW.stage_indexes IS NOT NULL AND array_length(NEW.stage_indexes, 1) >= 1 THEN
    NEW.stage_index := (SELECT MAX(s) FROM unnest(NEW.stage_indexes) AS s);
  END IF;
  RETURN NEW;
END;
$function$""",
    """CREATE OR REPLACE FUNCTION lessons.update_lessons_updated_at() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'lessons'
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$""",
    """CREATE OR REPLACE FUNCTION lessons.update_project_lessons_count() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'lessons'
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE lessons.projects SET lessons_count = (SELECT COUNT(*) FROM lessons.lessons WHERE project_id = NEW.project_id) WHERE id = NEW.project_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE lessons.projects SET lessons_count = (SELECT COUNT(*) FROM lessons.lessons WHERE project_id = OLD.project_id) WHERE id = OLD.project_id;
  ELSIF TG_OP = 'UPDATE' AND OLD.project_id IS DISTINCT FROM NEW.project_id THEN
    UPDATE lessons.projects SET lessons_count = (SELECT COUNT(*) FROM lessons.lessons WHERE project_id = OLD.project_id) WHERE id = OLD.project_id;
    UPDATE lessons.projects SET lessons_count = (SELECT COUNT(*) FROM lessons.lessons WHERE project_id = NEW.project_id) WHERE id = NEW.project_id;
  END IF;
  RETURN NULL;
END;
$function$""",
    # A group member must belong to a referent profile, never to a person.
    """CREATE OR REPLACE FUNCTION lessons.check_referent_member() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'lessons'
AS $function$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM lessons.profiles WHERE id = NEW.profile_id AND role = 'referent') THEN
    RAISE EXCEPTION 'profile % is not a referent group', NEW.profile_id;
  END IF;
  RETURN NEW;
END;
$function$""",
    ("CREATE OR REPLACE TRIGGER trg_update_project_lessons_count AFTER INSERT OR DELETE OR UPDATE ON lessons.lessons "
     "FOR EACH ROW EXECUTE FUNCTION lessons.update_project_lessons_count()"),
    ("CREATE OR REPLACE TRIGGER lessons_updated_at_trigger BEFORE UPDATE ON lessons.lessons "
     "FOR EACH ROW EXECUTE FUNCTION lessons.update_lessons_updated_at()"),
    ("CREATE OR REPLACE TRIGGER projects_sync_stage_index BEFORE INSERT OR UPDATE OF stage_indexes ON lessons.projects "
     "FOR EACH ROW EXECUTE FUNCTION lessons.sync_project_stage_index()"),
    ("CREATE OR REPLACE TRIGGER referent_members_check BEFORE INSERT OR UPDATE ON lessons.referent_members "
     "FOR EACH ROW EXECUTE FUNCTION lessons.check_referent_member()"),
)

SCHEMA_STATEMENTS: tuple[str, ...] = (
    "CREATE SCHEMA IF NOT EXISTS lessons",
    *(f"CREATE SEQUENCE IF NOT EXISTS lessons.{seq}" for seq, _ in _SEQUENCES),
    *_TABLE_DDL,
    # A schema created before these columns existed (create_all-style: CREATE
    # TABLE IF NOT EXISTS never alters) still gets them.
    "ALTER TABLE lessons.profiles ADD COLUMN IF NOT EXISTS shan_user_id integer REFERENCES public.users(id) ON DELETE SET NULL",
    "ALTER TABLE lessons.profiles ADD COLUMN IF NOT EXISTS is_login boolean NOT NULL DEFAULT true",
    "ALTER TABLE lessons.profiles DROP COLUMN IF EXISTS password",
    "ALTER TABLE lessons.projects ADD COLUMN IF NOT EXISTS shan_project_identifier varchar(100)",
    # Sequences must be OWNED BY their column, or pg_get_serial_sequence returns
    # NULL and the import's setval silently does nothing (found in testing).
    *(f"ALTER SEQUENCE lessons.{seq} OWNED BY lessons.{tbl}.id" for seq, tbl in _SEQUENCES),
    "CREATE INDEX IF NOT EXISTS idx_lesson_workflow_events_lesson ON lessons.lesson_workflow_events (lesson_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON lessons.activity_logs (created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON lessons.activity_logs (user_id)",
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_action_type ON lessons.activity_logs (action_type)",
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_entity_type ON lessons.activity_logs (entity_type)",
    "CREATE INDEX IF NOT EXISTS idx_lessons_profiles_shan_user ON lessons.profiles (shan_user_id)",
    "CREATE INDEX IF NOT EXISTS idx_lessons_referent_members_user ON lessons.referent_members (shan_user_id)",
    *_FUNCTION_DDL,
)

# lessons_anon gets the lessons schema and nothing else — no grant anywhere in
# here touches another schema. lesson_workflow_events is append-only (history
# is written through apply_lesson_workflow_event); referent_members is not
# PostgREST's at all.
ROLE_STATEMENTS: tuple[str, ...] = (
    f"""DO $$BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{ANON_ROLE}') THEN CREATE ROLE {ANON_ROLE} NOLOGIN; END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{AUTHENTICATOR_ROLE}') THEN CREATE ROLE {AUTHENTICATOR_ROLE} LOGIN NOINHERIT; END IF;
END$$""",
    f"GRANT {ANON_ROLE} TO {AUTHENTICATOR_ROLE}",
    f"GRANT USAGE ON SCHEMA lessons TO {ANON_ROLE}",
    f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lessons TO {ANON_ROLE}",
    f"REVOKE UPDATE, DELETE ON lessons.lesson_workflow_events FROM {ANON_ROLE}",
    f"REVOKE ALL ON lessons.referent_members FROM {ANON_ROLE}",
    f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lessons TO {ANON_ROLE}",
    f"GRANT EXECUTE ON FUNCTION lessons.apply_lesson_workflow_event(integer,text,text,text,text,text,jsonb,text,text,text) TO {ANON_ROLE}",
    "NOTIFY pgrst, 'reload schema'",
)

# The isolation proof, run against the live DB after the grants: every
# relation outside `lessons` that lessons_anon could read or write. Must be
# empty. A non-empty answer means some grant to PUBLIC leaks through — logged
# as an error and reported by GET /lessons/api/_status.
ISOLATION_CHECK = f"""
SELECT n.nspname || '.' || c.relname AS rel
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r', 'v', 'm', 'p', 'f')
  AND n.nspname NOT IN ('lessons', 'pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND (has_table_privilege('{ANON_ROLE}', c.oid, 'SELECT')
    OR has_table_privilege('{ANON_ROLE}', c.oid, 'INSERT')
    OR has_table_privilege('{ANON_ROLE}', c.oid, 'UPDATE')
    OR has_table_privilege('{ANON_ROLE}', c.oid, 'DELETE'))
ORDER BY 1
"""

# Only characters that need no quoting inside a SQL literal. ALTER ROLE takes
# no bind parameters, so anything else is refused rather than escaped.
_SAFE_PASSWORD = re.compile(r"^[A-Za-z0-9_\-]{16,128}$")


def authenticator_password_sql(password: str | None) -> str | None:
    """The ALTER ROLE statement for the PostgREST login, or None to skip."""
    if not password:
        return None
    if not _SAFE_PASSWORD.match(password):
        logger.error("LESSONS_PGRST_PASSWORD must be 16-128 chars of [A-Za-z0-9_-]; not applied")
        return None
    return f"ALTER ROLE {AUTHENTICATOR_ROLE} PASSWORD '{password}'"


async def ensure_schema(engine) -> dict:
    """Create/upgrade the lessons schema, roles and grants. Never raises.

    Returns a status dict (also kept for GET /lessons/api/_status):
    {schema: bool, roles: bool, leaks: list[str] | None, error: str | None}.
    """
    status: dict = {"schema": False, "roles": False, "leaks": None, "error": None}
    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT pg_advisory_xact_lock(:k)"), {"k": _ADVISORY_LOCK})
            for stmt in SCHEMA_STATEMENTS:
                await conn.execute(text(stmt))
        status["schema"] = True
    except Exception as e:  # noqa: BLE001 — a lessons failure must not stop Shan-AI booting
        status["error"] = f"schema: {e}"
        logger.error("lessons schema setup failed: %s", e)
        return status

    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT pg_advisory_xact_lock(:k)"), {"k": _ADVISORY_LOCK})
            for stmt in ROLE_STATEMENTS:
                await conn.execute(text(stmt))
            pw_sql = authenticator_password_sql(os.getenv("LESSONS_PGRST_PASSWORD"))
            if pw_sql:
                await conn.execute(text(pw_sql))
        status["roles"] = True
    except Exception as e:  # noqa: BLE001
        status["error"] = f"roles: {e}"
        logger.error("lessons roles/grants setup failed (needs CREATEROLE): %s", e)
        return status

    try:
        async with engine.connect() as conn:
            leaks = [r[0] for r in (await conn.execute(text(ISOLATION_CHECK))).all()]
        status["leaks"] = leaks
        if leaks:
            logger.error("lessons_anon can reach %d relation(s) outside schema lessons: %s",
                         len(leaks), ", ".join(leaks[:20]))
        else:
            logger.info("lessons schema ready; lessons_anon isolated to schema lessons")
    except Exception as e:  # noqa: BLE001
        status["error"] = f"isolation check: {e}"
        logger.error("lessons isolation check failed: %s", e)
    return status
